AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Planner Agent Serverless API

Parameters:
  ApiName:
    Type: String
    Default: planner-agent
  BucketName:
    Type: String
    Default: planner-agent-artifacts
  StageName:
    Type: String
    Default: dev
  LambdaExecutionRoleArn:
    Type: String

Globals:
  Function:
    Runtime: python3.12
    Timeout: 180
    MemorySize: 1024
    Tracing: Active
    Environment:
      Variables:
        LambdaExecutionRoleArn: !Ref LambdaExecutionRoleArn
        S3_BUCKET: !Ref BucketName
        STAGE: !Ref StageName
        CREW_LLM_MODEL: gpt-4o-mini

Resources:
  PlannerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref ApiName
      StageName: !Ref StageName
      TracingEnabled: true

  PlannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      # unique function name
      FunctionName: planner-agent
      Handler: planner_handler.lambda_handler
      CodeUri: ./        # point to the folder containing your code
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /planner/plan
            Method: post
            RestApiId: !Ref PlannerApi

  FinalFormatterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub final-formatter-agent
      Handler: final_formatter_handler.handler
      CodeUri: ./        # same CodeUri if the handler file is in planner_agent/
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /planner/final
            Method: post
            RestApiId: !Ref PlannerApi

Outputs:
  ApiUrl:
    Description: Invoke URL for the API
    Value: !Sub "https://${PlannerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/planner/plan"
  BucketNameOut:
    Value: !Ref BucketName
